parameters:
#    company_demo.example.class: Company\DemoBundle\Example

services:
#    company_demo.example:
#        class: %company_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
